### ISSUE TITLE
Implement Multiple Pseudofermions technique in the staggered RHMC algorithm

### ISSUE THREAD

**Issue by AxelKrypton** [AG-Philipsen/cl2qcd#17]
The design decisions explained in #1 should be followed.

**Comment by AxelKrypton** [comment]
In 5d27c413dea2c860a544ddebbae673a4aed9cb43 I started changing inheritance of the rooted staggered field from a staggered field to composition. At the moment a rooted staggered field contains a _trivial_ set of staggered field of dimension 1. Provided this object of an access operator, I propagated everywhere this modification, hard-coding a `[0]` everywhere it was required. Next steps:

- [ ] Introduce a parameter corresponding to the number of pseudofermionic fields (default 1)
- [ ] Where needed, loop over the pseudofermions

**Comment by francescacuteri** [comment]
With 5fda7cfbc805d8ade4ec72316082a86c2203f634 the implementation of loops over the pseudofermions everywhere needed, as well as of related tests, is completed. Functions affected, beyond the ctors of the Rooted_Staggeredfield_eo class, are in: fermion_force_staggered.cpp, metropolis.cpp, molecular_dynamics.cpp, rhmc.cpp.

Next step:
- [ ] Production test

**Comment by AxelKrypton** [comment]
In my ongoing simulations, I tried to figure out where the use of the multiple pseudofermions technique is advantageous and which kind of benefit it has. No meticulous test was done, just some simulations were run with and without multiple pseudofermions to get a rough idea. Clearly, the integration steps in the molecular dynamics part of the RHMC were reduced using the multiple pseudofermions in order to keep the acceptance always ~80% (while all the other parameters were kept fixed). As already expected reading [Clark Ph.D. thesis](https://www.era.lib.ed.ac.uk/handle/1842/13416), the multiple pseudofermions technique is expected to be advantageous only at very small masses and using a number of multiple pseudofermions smaller than the optimal one, which can be analytically estimated, gives usually a better time-per-trajectory improvement. 

Using as parameters
* &mu; = i&mu;<sub>i</sub><sup>RW</sup> 
* N<sub>f</sub> = 2 (staggered flavours)
* m = 0.006
* N<sub>t</sub> = 6
* N<sub>s</sub> = 30
* 2 time-scales each with the 2MN integrator in the MD part of the RHMC

it turned out that **2 pseudofermions** reduces the time per trajectory of **~12%** with respect to not using them.
